---
- hosts: all
  vars:
    openjdk_app: jre
  roles:
  - role: andrewrothstein.temurin
  - role: '{{ playbook_dir }}'
  tasks:
  - command: bash -lc 'gradle --version'
    register: gradle_test_output
  - name: gradle --version
    debug:
      msg: '{{ gradle_test_output.stdout }}'
