---
- hosts: all
  roles:
  - role: andrewrothstein.openjdk
    openjdk_app: jre
  - role: '{{ playbook_dir }}'
  tasks:
  - command: bash -l -c 'gradle --version'
    register: gradle_test_output
  - name: gradle --version
    debug:
      msg: '{{ gradle_test_output.stdout }}'
