---
- name: Look for gradle in {{ gradle_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ gradle_install_dir }}'
  changed_when: false
  register: gradle_binary
- name: Downloading an installing gradle
  when: not gradle_binary.stat.exists
  block:
    - name: Downloading {{ gradle_zip_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ gradle_zip_url }}'
        dest: '{{ gradle_tmp_zip }}'
        checksum: '{{ gradle_checksum }}'
        timeout: '{{ gradle_timeout_seconds }}'
        mode: '644'
    - name: Unarchiving {{ gradle_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ gradle_tmp_zip }}'
        dest: '{{ gradle_parent_install_dir }}'
        creates: '{{ gradle_install_dir }}'
  always:
    - name: Rm {{ gradle_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ gradle_tmp_zip }}'
        state: absent

- name: Linking {{ gradle_link }} to {{ gradle_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ gradle_exe }}'
    dest: '{{ gradle_link }}'
    state: link
