---
- include_role:
    name: andrewrothstein.unarchivedeps
- include_role:
    name: andrewrothstein.bash
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: install os dep pkgs
  become: true
  become_user: root
  package:
    state: present
    name:
      - findutils
- name: using installer {{ gradle_installer }}
  include_tasks: '{{ gradle_installer | default("bin") }}.yml'
